### PR TITLE
Revert "Revert "Revert "fsdafsa"""

### PR DESCRIPTION
**Pull request by alemone**
This reverts commit cdf6cbf85361029fed02fa7d4be39770f2d9e836.

### CODE REVIEW

**Comment by Ruuji** [comment]
Those changes are not acceptable to our commnuity guidelines. We have to include those informations or we are going to die.

**Comment by alemone** [comment]
No, they won't know, i use the force of gabeN and then we can do whatever we want. Fuck the guidelines as long as we get our Money.

**Comment by Ruuji** [comment]
But how can Gaben be real if money isn't real.

**Comment by alemone** [comment]
Money is more real than gabeN is.

IRL GabeN looks like this: http://www.gabeN.sexy

**Comment by Ruuji** [comment]
Omg, why are you posting a virus. You are banned from this server for negative behaviour.

**Comment by alemone** [comment]
Virus? It's NSFW Picture of the real GabeN, of a Paperazzi

**Pull request merged**
